pipeline {
    agent any

    stages {
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                sh 'mvn test'
            }
        }
    }
}
