
pipeline {
    agent any

    stages {
       stage('Test') {
            agent {
                docker {
                image 'python:3.6-slim'
                }
            }
            steps {
                sh 'pip install pytest'// Instalamos pytest dentro del contenedor Docker
                sh 'pytest'
            }
        }
    }
}